### PR TITLE
fix: Skip symbolic links when passing files to Prettier

### LINKED ISSUE #6378: Skip symbolic links when passing files to Prettier
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

image

Repro:
```shell
> file test.yaml
test.yaml: symbolic link to examples/account-request-template.yaml

> prettier -c ./test.yaml ; echo $?
Checking formatting...
[error] Explicitly specified pattern "./test.yaml" is a symbolic link.
All matched files use Prettier code style!
2
```

### Expected Behavior

`super-linter` should bypass `prettier` failure to scan symbolic links.

### Anything else?

There are two options that I envision:
* Add `--no-error-on-unmatched-pattern` cmdline flag to `PRETTIER_COMMAND=(prettier)` at https://github.com/super-linter/super-linter/blob/main/lib/functions/linterCommands.sh#L16
* Add test for input file to be plain file (or to be not a symlink) where `PRETTIER_COMMAND` is run for each particular type of input file

Option 1 looks simple, though may suppress something else (Prettier's docu is a bit vague saying just «_Prevent errors when pattern is unmatched_»: https://github.com/prettier/prettier/blob/main/docs/cli.md#user-content---no-error-on-unmatched-pattern)
The 2nd option looks a bit more robust, though would require change to the way files are passed to Prettier and may result in a more complex code change.

Please let me know which option looks best for you and I'll try and create PR for that. Thanks.

Refs:
* https://github.com/prettier/prettier/issues/15723
* https://github.com/prettier/prettier/issues/15843
* https://github.com/prettier/prettier/pull/15533
* https://prettier.io/docs/en/cli.html#file-patterns («_Prettier CLI will not follow symbolic links when expanding arguments_»)
* https://github.com/prettier/prettier/blob/main/docs/cli.md#user-content---no-error-on-unmatched-pattern
* https://github.com/prettier/prettier/blob/main/CHANGELOG.md#skip-explicitly-passed-symbolic-links-with---no-error-on-unmatched-pattern-15533-by-sanmai-nl

### PR DESCRIPTION
**Pull request by yermulnik**
Skip symbolic links when passing files to Prettier

- Fix #6378
- [`lib/functions/detectFiles.sh`]: Add `IsNotSymbolicLink()` function
  to check whether provided file is symbolic link or not
- [`lib/functions/buildFileList.sh`]: Use `IsNotSymbolicLink()` function
  to not add files that are symbolic links to the file array for
  Prettier
- [`test/lib/detectFilesTest.sh`]: Add test for `IsNotSymbolicLink()`
  function

## Readiness checklist

In order to have this pull request merged, complete the following tasks.

### Pull request author tasks

- [x] I checked that all workflows return a success.
- [x] I included all the needed documentation for this change.
- [x] I provided the necessary tests.
- [x] I squashed all the commits into a single commit.
- [x] I followed the
      [Conventional Commit v1.0.0 spec](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I wrote the necessary upgrade instructions in the
      [upgrade guide](../docs/upgrade-guide.md).
- [x] If this pull request is about and existing issue, I added the
      `Fix #ISSUE_NUMBER` or `Close #ISSUE_NUMBER` text to the description of
      the pull request.

### Super-linter maintainer tasks

- [ ] Label as `breaking` if this change breaks compatibility with the previous
      released version.
- [ ] Label as either: `automation`, `bug`, `documentation`, `enhancement`,
      `infrastructure`.
- [ ] Add the pull request to a milestone, eventually creating one, that matches
      with the version that release-please proposes in the
      `preview-release-notes` CI job.

### CODE REVIEW

File: lib/functions/detectFiles.sh [hunk 1]
```diff
@@ -269,6 +269,20 @@ function IsGenerated() {
   fi
 }
 
+function IsNotSymbolicLink() {
+  local FILE="$1"
+
+  debug "Checking if ${FILE} is not a symbolic link..."
+
+  if [[ -L ${FILE} ]]; then
```
Comment (ferrarimarco) [inline lib/functions/detectFiles.sh:277]: Double quote `${FILE}`

**Review by ferrarimarco — CHANGES_REQUESTED** [review]
Thanks for this PR.

Can you refactor the commit message to use only lowercase letters in the heading? Otherwise commitlint will complain.

Can you also please add a description to the commit? You can reuse what you wrote for the PR, including the reference to the fixed issue.

Thanks!

File: test/linters/README.md [hunk 2]
```diff
@@ -47,3 +47,8 @@ up.
 ### Ansible test cases
 
 `roles/ghe-initialize` is a valid Ansible role
+
+### Symbolic Links test cases
```
Comment (ferrarimarco) [inline test/linters/README.md:51]: Can you add a symbolic link in `test/linters/prettier/`? Ideally, we want to see the test failing, and then passing after committing your fix.

**Comment by ferrarimarco** [comment]
@yermulnik Thanks for working on this. We would need to have a single commit, once you are done iterating on the PR.

**Comment by yermulnik** [comment]
> @yermulnik Thanks for working on this. We would need to have a single commit, once you are done iterating on the PR.

Yeah, this is what I'm trying to figure out right now 👍🏻

File: test/linters/README.md (hunk 2 above)
Comment (yermulnik) [reply test/linters/README.md:51]: > I was asking to create a symbolic link in `test/linter/prettier` so we can see that it's being skipped.

Will create. Is it going to be automaGically passed to Prettier within tests? 🤔

Comment (yermulnik) [reply test/linters/README.md:51]: Added

**Comment by yermulnik** [comment]
> > @yermulnik Thanks for working on this. We would need to have a single commit, once you are done iterating on the PR.
> 
> Yeah, this is what I'm trying to figure out right now 👍🏻

@ferrarimarco Done

File: test/linters/README.md (hunk 2 above)
Comment (yermulnik) [reply test/linters/README.md:51]: JSCPD found a clone 🤷🏻 Not sure what symlink should point to to avoid vlone detection.
A broken symlink would not be a clone, but having broken link in the repo is somewhat strange. What would you suggest?

I also can see this:
```
2025-03-03T17:52:23.2605712Z 2025-03-03 17:52:22 [DEBUG]   FILTER_REGEX_INCLUDE: , FILTER_REGEX_EXCLUDE: .*(/test/linters/|CHANGELOG.md).*, TEST_CASE_RUN: false
2025-03-03T17:52:23.2609756Z 2025-03-03 17:52:22 [DEBUG]   FILE: /tmp/lint/test/linters/prettier/README.md, FILE_TYPE: md, BASE_FILE: readme.md, FILE_DIR_NAME: /tmp/lint/test/linters/prettier
2025-03-03T17:52:23.2609997Z 2025-03-03 17:52:22 [DEBUG]   FILTER_REGEX_EXCLUDE match. Skipping /tmp/lint/test/linters/prettier/README.md
```
Is it that you meant exactly `test/linter/prettier` (`linter` vs `linters`)? I thought it was a typo and created `test/linters/prettier/README.md` 🤔

Comment (ferrarimarco) [reply test/linters/README.md:51]: Yeah, it was a typo.

Can you add an exclusion for `"**/test/linters/prettier"` to https://github.com/super-linter/super-linter/blob/main/.github/linters/.jscpd.json ? So that JSCPD doesn't complain

thanks

File: test/linters/prettier/test_symlink.md [hunk 3]
```diff
@@ -0,0 +1 @@
+../README.md
```
Comment (ferrarimarco) [inline test/linters/prettier/test_symlink.md:1]: Can you rename this file to `test_symlink_good.md`? Otherwise it doesn't get picked up by the test logic. Thanks!

Comment (yermulnik) [reply test/linters/prettier/test_symlink.md]: Done

File: lib/functions/buildFileList.sh [hunk 4]
```diff
@@ -369,7 +369,7 @@ BuildFileArrays() {
     elif [ "${FILE_TYPE}" == "css" ] || [ "${FILE_TYPE}" == "scss" ] ||
       [ "${FILE_TYPE}" == "sass" ]; then
       echo "${FILE}" >>"${FILE_ARRAYS_DIRECTORY_PATH}/file-array-CSS"
-      echo "${FILE}" >>"${FILE_ARRAYS_DIRECTORY_PATH}/file-array-CSS_PRETTIER"
+      IsNotSymbolicLink "${FILE}" && echo "${FILE}" >>"${FILE_ARRAYS_DIRECTORY_PATH}/file-array-CSS_PRETTIER"
```
Comment (ferrarimarco) [inline lib/functions/buildFileList.sh:372]: I think we need a minor refactoring on those if conditions. The log says:

```
2025-03-04 21:52:59 [DEBUG]   /tmp/lint/test/linters/prettier/test_symlink_good.md is a symbolic link
```

But it doesn't explain that the file is going to be skipped.

Maybe we can refactor those `IsNotSymbolicLink "${FILE}" && echo "${FILE}" >>"${FILE_ARRAYS_DIRECTORY_PATH}/file-array-XXX_PRETTIER"` to something like:

```bash
if IsNotSymbolicLink "${FILE}"; then
  echo "${FILE}" >>"${FILE_ARRAYS_DIRECTORY_PATH}/file-array-XXX_PRETTIER"
else
  debug "${FILE} is a symbolic link. Skip adding to XXX_PRETTIER file array beacuse Prettier doesn't support following symbolic links."
fi
```

**Review by ferrarimarco — CHANGES_REQUESTED** [review]
Just a minor thing to address. It seems that the check is working as expected.

File: lib/functions/buildFileList.sh (hunk 4 above)
Comment (yermulnik) [reply lib/functions/buildFileList.sh]: Yep, agree. Done.

Comment (yermulnik) [reply lib/functions/buildFileList.sh]: I also adjusted a debug message a bit to make it not duplicate the same message from the check.
Let me know if it looks okay.

Comment (ferrarimarco) [reply lib/functions/buildFileList.sh]: Thanks!

**Review by ferrarimarco — APPROVED** [review]

File: lib/functions/buildFileList.sh (hunk 4 above)
Comment (yermulnik) [reply lib/functions/buildFileList.sh]: Thanks for guidance and valuable suggestions 🤝
