### PR TITLE
fix: update deprecated default file name for editorconfig

### LINKED ISSUE #6616: EDITORCONFIG_FILE_NAME points to deprecated filename
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [x] I am using the latest Super-linter version.
- [x] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [x] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [x] I think that this is a Super-linter issue.

### Current Behavior

With default settings and a `.github/linters/.ecrc` file, warning messages now appear:

    The default configuration file name `.ecrc` is deprecated. Use `.editorconfig-checker.json` instead. You can simply rename it

### Expected Behavior

EDITORCONFIG_FILE_NAME should be set to `.editorconfig-checker.json` by default rather than `.ecrc`. 

editorconfig's [readme](https://github.com/editorconfig-checker/editorconfig-checker?tab=readme-ov-file#configuration) states:

> The configuration is done via arguments or it will take the first config file found with the following file names:

> .editorconfig-checker.json. 
.ecrc **(deprecated filename, soon unsupported)**

emphasis mine.

### Super-Linter version

```markdown
v7.3.0
```

### Super-linter configuration

```yaml
# note: 
# /.github/linters/.ecrc must exist
# /.editorconfig must exist

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      packages: read
      statuses: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: "super-linter/super-linter@v7" # can be v7.3.0 if you prefer
        env:
          VALIDATE_EDITORCONFIG: true
```

### Relevant log output

```shell
------
Error: -27 00:18:27 [ERROR]   Errors found in EDITORCONFIG
Error: -27 00:18:27 [ERROR]   Stdout contents for EDITORCONFIG:
------
The default configuration file name `.ecrc` is deprecated. Use `.editorconfig-checker.json` instead. You can simply rename it
Error: -27 00:18:30 [ERROR]   Super-linter detected linting errors
super-linter-output/super-linter-summary.md 57ms
```

### Steps To Reproduce

create minimal /.github/linters/.ecrc
create minimal /.editorconfig
run super-linter over a codebase with VALIDATE_EDITORCONFIG: true
see warning 

### Anything else?

https://github.com/editorconfig-checker/editorconfig-checker?tab=readme-ov-file#configuration

### PR DESCRIPTION
**Pull request by anishadas2022**
- Update default file name for `EDITORCONFIG_FILE_NAME` to be changed from `.ecrc` (deprecated) to `.editorconfig-checker.json`.
- Also update relevant references to .ecrc to .editorconfig-checker.json

See [editorconfig-checker documentation](https://github.com/editorconfig-checker/editorconfig-checker?tab=readme-ov-file#configuration) for the default file name change 

Fix #6616 

## Readiness checklist

In order to have this pull request merged, complete the following tasks.

### Pull request author tasks

- [ ] I checked that all workflows return a success.
- [x] I included all the needed documentation for this change.
- [x] I provided the necessary tests.
- [x] I squashed all the commits into a single commit.
- [x] I followed the
      [Conventional Commit v1.0.0 spec](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I wrote the necessary upgrade instructions in the
      [upgrade guide](../docs/upgrade-guide.md).
- [x] If this pull request is about and existing issue, I added the
      `Fix #ISSUE_NUMBER` or `Close #ISSUE_NUMBER` text to the description of
      the pull request.

### Super-linter maintainer tasks

- [x] Label as `breaking` if this change breaks compatibility with the previous
      released version.
- [x] Label as either: `automation`, `bug`, `documentation`, `enhancement`,
      `infrastructure`.
- [x] Add the pull request to a milestone, eventually creating one, that matches
      with the version that release-please proposes in the
      `preview-release-notes` CI job.

### CODE REVIEW

**Review by ferrarimarco — CHANGES_REQUESTED** [review]
Thanks for this PR.

Can you please refactor the commit message and the PR description to include a reference to the editorconfig-checker documentation about the default name change? So we don't lose context. Thanks.

**Comment by anishadas2022** [comment]
> Thanks for this PR.
> 
> Can you please refactor the commit message and the PR description to include a reference to the editorconfig-checker documentation about the default name change? So we don't lose context. Thanks.

Hey, thanks for the review. I've updated the PR and commit descriptions with your suggestions

**Comment by ferrarimarco** [comment]
Hi! There are [two linting failures](https://github.com/super-linter/super-linter/actions/runs/14616356008/job/41034360852?pr=6730). Can you please have a look? Thanks!

File: lib/globals/linterRules.sh [hunk 1]
```diff
@@ -19,7 +19,7 @@ CLOUDFORMATION_FILE_NAME=".cfnlintrc.yml"
 COFFEESCRIPT_FILE_NAME=".coffee-lint.json"
 CSS_FILE_NAME="${CSS_FILE_NAME:-.stylelintrc.json}"
 DOCKERFILE_HADOLINT_FILE_NAME="${DOCKERFILE_HADOLINT_FILE_NAME:-.hadolint.yaml}"
-EDITORCONFIG_FILE_NAME="${EDITORCONFIG_FILE_NAME:-.ecrc}"
```
Comment (ferrarimarco) [inline lib/globals/linterRules.sh:22]: As this is implemented, it's a breaking change. Let me think if how we can make it a non-breaking change, or at least require explicit user action.

Comment (ferrarimarco) [reply lib/globals/linterRules.sh:22]: Otherwise, users that rely on the old value being set, will see their editorconfig-checker configuration silently ignored

**Comment by ferrarimarco** [comment]
I've updated this PR to include some validation checks, so users can act and update the name of the editorconfig-checker configuration file name.
